"""
Auto-generated standalone scorecard (no optbinning dependency).

Requires ``numpy``. Generated by predictive-model-agent ``writre_production_code``.
"""

from __future__ import annotations

from math import isnan
from typing import Any, Mapping

import numpy as np


_INTERCEPT = 0.0
_VARIABLE_ORDER = ['ExternalRiskEstimate', 'MSinceOldestTradeOpen', 'MSinceMostRecentTradeOpen', 'AverageMInFile', 'NumSatisfactoryTrades', 'NumTrades60Ever2DerogPubRec', 'NumTrades90Ever2DerogPubRec', 'PercentTradesNeverDelq', 'MSinceMostRecentDelq', 'MaxDelq2PublicRecLast12M', 'MaxDelqEver', 'NumTotalTrades', 'NumTradesOpeninLast12M', 'PercentInstallTrades', 'MSinceMostRecentInqexcl7days', 'NumInqLast6M', 'NumInqLast6Mexcl7days', 'NetFractionRevolvingBurden', 'NetFractionInstallBurden', 'NumRevolvingTradesWBalance', 'NumInstallTradesWBalance', 'NumBank2NatlTradesWHighUtilization', 'PercentTradesWBalance']
_VARS = {
    'ExternalRiskEstimate': {
        'dtype': 'numerical',
        'numerical_splits': [62.5, 64.5, 68.5, 70.5, 72.5, 74.5, 76.5, 80.5, 84.5, 87.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 11,
        'n_special': 1,
        'idx_missing': 12,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [30.718232727393037, 30.49182053102431, 26.67139718704712, 24.10026548210411, 21.364948522670467, 21.323924847647508, 17.473157599312387, 15.399503962683202, 11.896482780778927, 10.012981552924222, 9.326697455625427, 21.19408485641542, 21.19408485641542],
        'woe': [1.219375952462631, 1.190388415589379, 0.7012598954339608, 0.3720780920754273, 0.02187566264231268, 0.01662340454192457, -0.4763900434599663, -0.7418797662673428, -1.1903713109227538, -1.4315158347996304, -1.5193807373757153, 0.0, 0.0],
    },
    'MSinceOldestTradeOpen': {
        'dtype': 'numerical',
        'numerical_splits': [31.5, 82.5, 107.5, 134.5, 169.5, 212.5, 273.5, 367.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 9,
        'n_special': 1,
        'idx_missing': 10,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [19.67276262586623, 29.627575268640975, 31.442883329209998, 25.93877336363501, 21.69148695481061, 21.205793028639604, 19.234003962984435, 15.641941219736527, 14.172835177069508, 21.19408485641542, 21.19408485641542],
        'woe': [-0.16872836390249918, 0.9353501912139607, 1.1366842366175176, 0.5262287719026856, 0.055166381308707976, 0.0012985419551532693, -0.21739065900967633, -0.6157828322999795, -0.7787199497632524, 0.0, 0.0],
    },
    'MSinceMostRecentTradeOpen': {
        'dtype': 'numerical',
        'numerical_splits': [2.5, 3.5, 7.5, 9.5, 16.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 6,
        'n_special': 1,
        'idx_missing': 7,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [21.579911344410256, 22.278298782786717, 21.441334259809874, 21.07371198824098, 20.71543649339724, 19.905389734382297, 21.19408485641542, 21.19408485641542],
        'woe': [0.10701410821141896, 0.3007211532935954, 0.06857791062395104, -0.033387016032737055, -0.13275948984594066, -0.35743673265539266, 0.0, 0.0],
    },
    'AverageMInFile': {
        'dtype': 'numerical',
        'numerical_splits': [41.5, 52.5, 65.5, 71.5, 80.5, 84.5, 97.5, 107.5, 137.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 10,
        'n_special': 1,
        'idx_missing': 11,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [32.96522366405907, 32.86723677697873, 28.03353657640147, 21.105583785594813, 19.966094012745806, 16.986301520940465, 16.497498384092033, 11.86482449668379, 11.663346317871579, 9.04752522200961, 21.19408485641542, 21.19408485641542],
        'woe': [0.7964431513140756, 0.789813292775406, 0.46276189331732076, -0.005988041844622708, -0.0830866845850097, -0.2847014443136433, -0.31777419258766515, -0.6312240167883575, -0.6448561655784151, -0.8218443763970071, 0.0, 0.0],
    },
    'NumSatisfactoryTrades': {
        'dtype': 'numerical',
        'numerical_splits': [5.5, 9.5, 11.5, 19.5, 23.5, 39.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 7,
        'n_special': 1,
        'idx_missing': 8,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [33.368341832667824, 28.988524728171555, 26.11022157854832, 20.96398026582423, 19.189925771709213, 17.439514493328296, 14.601019583737823, 21.19408485641542, 21.19408485641542],
        'woe': [0.6755085214953473, 0.43248721987098715, 0.27277987109314705, -0.012767728830001664, -0.11120403838954482, -0.20832846552906917, -0.36582698912601164, 0.0, 0.0],
    },
    'NumTrades60Ever2DerogPubRec': {
        'dtype': 'numerical',
        'numerical_splits': [0.5, 1.5, 2.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 4,
        'n_special': 1,
        'idx_missing': 5,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [19.929317805061704, 23.636599623518663, 24.99828537862581, 25.85357813572303, 21.19408485641542, 21.19408485641542],
        'woe': [-0.26669768470239125, 0.5150458596629401, 0.8021805045689767, 0.9825335567902594, 0.0, 0.0],
    },
    'NumTrades90Ever2DerogPubRec': {
        'dtype': 'numerical',
        'numerical_splits': [0.5, 1.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 3,
        'n_special': 1,
        'idx_missing': 4,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [21.14348095563581, 21.372503614873885, 21.424288112665074, 21.19408485641542, 21.19408485641542],
        'woe': [-0.1799432881288305, 0.6344423565429185, 0.818583750053859, 0.0, 0.0],
    },
    'PercentTradesNeverDelq': {
        'dtype': 'numerical',
        'numerical_splits': [63.5, 75.5, 83.5, 90.5, 95.5, 97.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 7,
        'n_special': 1,
        'idx_missing': 8,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [25.09803249641531, 31.828111090283905, 29.0279951241968, 26.069129167303533, 22.81396402854253, 18.741176279045877, 17.32241430335186, 21.19408485641542, 21.19408485641542],
        'woe': [0.4884884439198386, 1.3306015875728554, 0.9802320598019799, 0.6099986549681444, 0.20269028406604114, -0.3069245810983531, -0.4844497155797741, 0.0, 0.0],
    },
    'MSinceMostRecentDelq': {
        'dtype': 'numerical',
        'numerical_splits': [-3.5, 2.5, 15.5, 22.5, 32.5, 46.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 7,
        'n_special': 1,
        'idx_missing': 8,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [12.265576094087278, 42.54981005759004, 37.05917514032758, 30.90770996371085, 25.463806248237397, 20.57151969966492, 14.262784058706147, 21.19408485641542, 21.19408485641542],
        'woe': [-0.47881938454796724, 1.1452679803089092, 0.8508154012899174, 0.5209237196729926, 0.22897724843475423, -0.033387016032737055, -0.3717128213032731, 0.0, 0.0],
    },
    'MaxDelq2PublicRecLast12M': {
        'dtype': 'numerical',
        'numerical_splits': [1.5, 5.5, 6.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 4,
        'n_special': 1,
        'idx_missing': 5,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [21.138044687918843, 21.004633029543633, 21.18918942360068, 21.291710047054444, 21.19408485641542, 21.19408485641542],
        'woe': [0.2837089416253372, 0.9591187666408247, 0.02478361682213122, -0.49423726329198525, 0.0, 0.0],
    },
    'MaxDelqEver': {
        'dtype': 'numerical',
        'numerical_splits': [3.5, 5.5, 6.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 4,
        'n_special': 1,
        'idx_missing': 5,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [17.64059081937971, 16.647058601689192, 19.27494090355171, 24.476058626214304, 21.19408485641542, 21.19408485641542],
        'woe': [0.5191782139060189, 0.6643368315546199, 0.2803938093864051, -0.4795081297820305, 0.0, 0.0],
    },
    'NumTotalTrades': {
        'dtype': 'numerical',
        'numerical_splits': [8.5, 11.5, 16.5, 21.5, 24.5, 29.5, 45.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 8,
        'n_special': 1,
        'idx_missing': 9,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [23.245233235160132, 22.259677797888866, 21.438159156327607, 21.395739074635316, 21.113075792475097, 20.48984183983259, 20.31586847471178, 17.341876806137368, 21.19408485641542, 21.19408485641542],
        'woe': [0.24956691522309785, 0.1296526112117674, 0.029696959393839817, 0.024535631699967454, -0.009856518622543019, -0.08568651543558573, -0.1068541679146098, -0.46870508729058236, 0.0, 0.0],
    },
    'NumTradesOpeninLast12M': {
        'dtype': 'numerical',
        'numerical_splits': [0.5, 1.5, 2.5, 3.5, 5.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 6,
        'n_special': 1,
        'idx_missing': 7,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [20.238282531455503, 21.06937405497885, 21.2194066080285, 21.719720973953887, 21.98361703662485, 23.8283085287015, 21.19408485641542, 21.19408485641542],
        'woe': [-0.2558831085998225, -0.033387016032737055, 0.006779025692597598, 0.14072094222382894, 0.21137001170200986, 0.7052225386039657, 0.0, 0.0],
    },
    'PercentInstallTrades': {
        'dtype': 'numerical',
        'numerical_splits': [24.5, 35.5, 42.5, 46.5, 65.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 6,
        'n_special': 1,
        'idx_missing': 7,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [15.595277772577218, 18.94932596805246, 21.967674335683427, 22.471132126691842, 30.810637097702667, 36.02111940197, 21.19408485641542, 21.19408485641542],
        'woe': [-0.34125863782073473, -0.13682260328097923, 0.04715184645127535, 0.07783861907748735, 0.5861483471839621, 0.9037378027442599, 0.0, 0.0],
    },
    'MSinceMostRecentInqexcl7days': {
        'dtype': 'numerical',
        'numerical_splits': [-7.5, -3.5, 0.5, 1.5, 7.5, 12.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 7,
        'n_special': 1,
        'idx_missing': 8,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [-4.094988316846617, 29.054023022866616, 28.719251175060297, 20.413607446821253, 13.133814918886406, 8.364445542494996, 7.069511610230752, 21.19408485641542, 21.19408485641542],
        'woe': [-1.4321038971511848, 0.44510322709031724, 0.42614531334570316, -0.044197932136952674, -0.45644788603128095, -0.7265341965926824, -0.7998654696782322, 0.0, 0.0],
    },
    'NumInqLast6M': {
        'dtype': 'numerical',
        'numerical_splits': [0.5, 1.5, 2.5, 4.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 5,
        'n_special': 1,
        'idx_missing': 6,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [18.65437362786029, 21.488233431618227, 21.65176510985821, 24.4105344880555, 28.839726407606594, 21.19408485641542, 21.19408485641542],
        'woe': [-0.3361573881357198, 0.03893364554688923, 0.060578776385594266, 0.42573080556774734, 1.0119807581165605, 0.0, 0.0],
    },
    'NumInqLast6Mexcl7days': {
        'dtype': 'numerical',
        'numerical_splits': [0.5, 1.5, 2.5, 4.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 5,
        'n_special': 1,
        'idx_missing': 6,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [21.543282914539596, 21.180308120359605, 21.12401819446856, 20.626961181863994, 20.08863339184217, 21.19408485641542, 21.19408485641542],
        'woe': [-0.29397579782899186, 0.011598079884072049, 0.058986304098278014, 0.47743860773325353, 0.930635118662608, 0.0, 0.0],
    },
    'NetFractionRevolvingBurden': {
        'dtype': 'numerical',
        'numerical_splits': [6.5, 14.5, 20.5, 26.5, 39.5, 54.5, 65.5, 75.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 9,
        'n_special': 1,
        'idx_missing': 10,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [11.082395897659358, 11.897296849353138, 15.497730726718032, 17.226078341483273, 23.974168383012447, 26.640026997477715, 27.77940816555101, 38.023445871150685, 41.568883778445354, 21.19408485641542, 21.19408485641542],
        'woe': [-0.7421073700556526, -0.6823009416158567, -0.4180613544718277, -0.2912161253348369, 0.20403322163815557, 0.3996833581673159, 0.4833037271856516, 1.2351243094307702, 1.4953276851289221, 0.0, 0.0],
    },
    'NetFractionInstallBurden': {
        'dtype': 'numerical',
        'numerical_splits': [7.5, 33.5, 61.5, 72.5, 93.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 6,
        'n_special': 1,
        'idx_missing': 7,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [20.515671489832332, 19.34340688160248, 21.039790436990966, 21.81165653065207, 21.91724907580763, 22.681218140965942, 21.19408485641542, 21.19408485641542],
        'woe': [-0.21258844549044806, -0.579930722400807, -0.04834988870944966, 0.19352301807694944, 0.2266116276706269, 0.4660099119096307, 0.0, 0.0],
    },
    'NumRevolvingTradesWBalance': {
        'dtype': 'numerical',
        'numerical_splits': [0.5, 1.5, 2.5, 3.5, 4.5, 6.5, 7.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 8,
        'n_special': 1,
        'idx_missing': 9,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [21.969629334799173, 20.341373542186002, 14.701493564706222, 18.315878277355456, 19.28534205235492, 24.080874802976666, 27.274159088078314, 31.8074048257941, 21.19408485641542, 21.19408485641542],
        'woe': [0.04665569164079951, -0.05129794259926716, -0.39058538317106695, -0.17314895840789565, -0.11482734797291147, 0.17366532201893467, 0.3657689228821628, 0.6384827660799233, 0.0, 0.0],
    },
    'NumInstallTradesWBalance': {
        'dtype': 'numerical',
        'numerical_splits': [-3.5, 1.5, 2.5, 3.5, 4.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 6,
        'n_special': 1,
        'idx_missing': 7,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [25.92098701679613, 22.143469643946634, 21.69418139909784, 19.642988753739694, 17.503851232708055, 17.187370132108082, 21.19408485641542, 21.19408485641542],
        'woe': [-0.4155952619766341, -0.08347112043014834, -0.04396912536327403, 0.13637434608769947, 0.324450043086173, 0.35227546477924765, 0.0, 0.0],
    },
    'NumBank2NatlTradesWHighUtilization': {
        'dtype': 'numerical',
        'numerical_splits': [0.5, 1.5, 2.5, 3.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 5,
        'n_special': 1,
        'idx_missing': 6,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [20.303270781512094, 21.72958157646417, 22.188652385404648, 22.79630256703433, 23.610423105892327, 21.19408485641542, 21.19408485641542],
        'woe': [-0.4230270829965046, 0.25429505641904393, 0.47229720823283483, 0.7608562813985771, 1.1474633708723447, 0.0, 0.0],
    },
    'PercentTradesWBalance': {
        'dtype': 'numerical',
        'numerical_splits': [32.5, 44.5, 64.5, 75.5, 84.5, 89.5],
        'categorical_bins': [],
        'special_codes': None,
        'n_bins': 7,
        'n_special': 1,
        'idx_missing': 8,
        'idx_special_single': None,
        'idx_special_map': {},
        'points': [19.467815365757318, 19.842913131392848, 20.56946094444466, 21.43516481064828, 21.843755644988043, 22.34811070880349, 23.190888737434026, 21.19408485641542, 21.19408485641542],
        'woe': [-0.959465754273055, -0.7509852924568463, -0.3471678414518794, 0.13399296076301867, 0.36108897049983224, 0.6414110258590118, 1.1098295788721266, 0.0, 0.0],
    },
}


def _is_missing(value: Any) -> bool:
    if value is None:
        return True
    if isinstance(value, float) and isnan(value):
        return True
    if isinstance(value, np.generic) and np.issubdtype(value.dtype, np.floating):
        return bool(np.isnan(value))
    return False


def _digitize_right_false(x: float, splits: list[float]) -> int:
    """Same bin index as ``numpy.digitize(x, splits, right=False)`` (optbinning)."""
    if not splits:
        return 0
    return int(np.digitize(np.float64(x), np.asarray(splits, dtype=np.float64), right=False))


def _special_bin_index(value: Any, cfg: dict[str, Any]) -> int | None:
    sc = cfg["special_codes"]
    if sc is None:
        return None
    if isinstance(sc, dict):
        for key, codes in sc.items():
            seq = codes if isinstance(codes, (list, tuple)) else [codes]
            for code in seq:
                if value == code:
                    return cfg["idx_special_map"][str(key)]
                if (
                    isinstance(value, float)
                    and isinstance(code, float)
                    and isnan(value)
                    and isnan(code)
                ):
                    return cfg["idx_special_map"][str(key)]
        return None
    seq = sc if isinstance(sc, (list, tuple)) else [sc]
    for code in seq:
        if value == code:
            return cfg["idx_special_single"]
        if (
            isinstance(value, float)
            and isinstance(code, float)
            and isnan(value)
            and isnan(code)
        ):
            return cfg["idx_special_single"]
    return None


def _bin_index(name: str, value: Any) -> int:
    cfg = _VARS[name]
    if _is_missing(value):
        return cfg["idx_missing"]
    sp_idx = _special_bin_index(value, cfg)
    if sp_idx is not None:
        return sp_idx

    if cfg["dtype"] == "numerical":
        x = float(value)
        return _digitize_right_false(x, cfg["numerical_splits"])

    for i, cats in enumerate(cfg["categorical_bins"]):
        if value in cats:
            return i
        sval = str(value)
        for c in cats:
            if sval == str(c):
                return i
    return -1


class StandaloneScorecard:
    """Pure-Python PDO scorecard mirroring a fitted optbinning ``Scorecard``."""

    def __init__(self) -> None:
        """Stateless wrapper; all rules live in module-level ``_VARS``."""
        pass

    def get_score(self, dict_features: Mapping[str, Any]) -> dict[str, float]:
        total = _INTERCEPT
        for name in _VARIABLE_ORDER:
            idx = _bin_index(name, dict_features.get(name))
            pts = _VARS[name]["points"]
            if idx < 0:
                pick = pts[-1]
            else:
                pick = pts[idx]
            total += pick
        return {"score": float(total)}

    def get_woe(self, dict_features: Mapping[str, Any]) -> dict[str, float]:
        out: dict[str, float] = {}
        for name in _VARIABLE_ORDER:
            idx = _bin_index(name, dict_features.get(name))
            w = _VARS[name]["woe"]
            if idx < 0:
                out[name] = float(w[-1])
            else:
                out[name] = float(w[idx])
        return out


_DEFAULT_MODEL = StandaloneScorecard()


def get_score(dict_features: Mapping[str, Any]) -> dict[str, float]:
    """Module-level score using the embedded scorecard rules."""
    return _DEFAULT_MODEL.get_score(dict_features)


def get_woe(dict_features: Mapping[str, Any]) -> dict[str, float]:
    """Module-level WoE using the embedded scorecard rules."""
    return _DEFAULT_MODEL.get_woe(dict_features)
